version: '3.8'

services:
  postgres:
    image: postgres
    container_name: vehicle_management_pgDB
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: vehicleManageDB
      POSTGRES_INITDB_ARGS: "--data-checksums"
      TZ: Asia/Shanghai
    ports:
      - "5432:5432"
    volumes:
      - /home/docker_directory/postgres/data:/var/lib/postgresql/data
      - /home/docker_directory/postgres/init-scripts:/docker-entrypoint-initdb.d:ro
      - /home/docker_directory/postgres/backup:/backup
    restart: always
    user: "999:999"

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    hostname: rabbitmq-host
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - /home/docker_directory/rabbitmq/data:/var/lib/rabbitmq
        # - /home/docker_directory/rabbitmq/logs:/var/log/rabbitmq
    restart: unless-stopped
