#ifndef PORT_H
#define PORT_H

#define USER_MANAGE_PORT 8081
#define ORDER_MANAGE_PORT 8083
#define DISPATCH_MANAGE_PORT 8084
#define CONTAINER_MANAGE_PORT 8085
#define FINANCE_MANAGE_PORT 8086

#endif